language: "node_js"
node_js:
  - "5"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  - node_modules/.bin/karma karma start karma.conf.js --browsers=Chrome
notifications:
  slack: fellowshipofthecode:qWpjO7JR3sUskrGMLVTbOlYf
  email: false
